In [25]:
import numpy as np
#creating arrays
#1.Create a rank 2 (2D) array that resembles the matrix below.
#[[11 12 13 14]
#[15 16 17 18]]
the_2d_array=np.array([[11,12,13,14],[15,16,17,18]])
print('1:')
print(the_2d_array,'\n')
#use the appropriate functions to solve the following questions
#1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
#[[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]]
first_array=np.zeros((4,3))
print('2:',first_array,'\n')
#2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
#[[1. 1. 1. 1.]
#[1. 1. 1. 1.]
#[1. 1. 1. 1.]]
second_array=np.ones((3,4))
print('3:',second_array,'\n')


1:
[[11 12 13 14]
 [15 16 17 18]] 

2: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

3: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
