In [33]:
import numpy as np

#creating arrays
#1.Create a rank 2 (2D) array that resembles the matrix below.
#[[11 12 13 14]
#[15 16 17 18]]
print('Creating arrays')
the_2d_array=np.array([[11,12,13,14],[15,16,17,18]])
print('1:')
print(the_2d_array,'\n')

#use the appropriate functions to solve the following questions
#1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
#[[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]]
print('Use the appropriate functions to solve the following questions')
first_array=np.zeros((4,3))
print('1:',first_array,'\n')

#2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
#[[1. 1. 1. 1.]
#[1. 1. 1. 1.]
#[1. 1. 1. 1.]]
second_array=np.ones((3,4))
print('2:')
print(second_array,'\n')

#3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
#[4 5 6 7 8 9 10 11 12 13]
third_array=np.array([[4,5,6,7,8,9,10,11,12,13]])
print('3:')
print(third_array,'\n')

#4. Create an array containing
#[0., 1.5, 3., 4.5]
fourth_array=np.array([0,1.5,3,4.5],dtype=np.double)
print('4:')
print(fourth_array,'\n')

#5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
#[[4 4]
#[4 4]]
fifth_array=np.full((2,2),4)
print('5: ')
print(fifth_array,'\n')

#6
#Create 2 matrices:
#i. Identity matrix of size 4
#[[1. 0. 0. 0.]
#[0. 1. 0. 0.]
#[0. 0. 1. 0.]
#[0. 0. 0. 1.]]
#ii. Diagonal matrix with [10,12] as the diagonals
#[[10  0]
#[ 0 12]]
matrix=np.eye(4)
print('6i: ')
print(matrix,'\n')

diagonal_nums=[10,12]
diagonal_matrix=np.diag(diagonal_nums)
print('6ii: ')
print(diagonal_matrix,'\n')

#7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is
# random but it should look something like this:
#[[6.3685612  0.61720883 8.93157783]
#[3.69927617 5.79879583 7.62145626]
#[7.21895112 4.02011535 4.48844787]]
random_array=np.random.uniform(0,10,size=(3,3))
print('7: ')
print(random_array,'\n')

#8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
#[[19 11 13]
#[10 11 13]
#[11 14 10]]
random_array2=np.random.randint(10,20,size=(3,3))
print('8: ')
print(random_array2,'\n')

#Slicing arrays
#1. Use this array for the following practice:
#myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
#a. Get a subarray of the first row and first 2 columns. Your results should look like this:
#[11 12]
#b. Change all elements in 1st and second row to 0. Your results should look like this:
#[[ 0  0  0]
# [ 0  0  0]
# [17 18 19]]
print('Slicing arrays')
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print('1a: ')
print(myArray[:1,:2],'\n')
print('1b: ')
myArray[:2,:3]=0
print(myArray,'\n')

#2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.
bigarray=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print('2: ')
print(bigarray[::-1],'\n')

#RESHAPING
#Use this array for the following practice:
#myArray = np.array([[11,12,13], [14,15,16]])
#Reshape the array to an array with 3 rows. Your results should look like this:
#[[11 12]
#[13 14]
#[15 16]]
print('Reshaping')
print('1: ')
myArray = np.array([[11,12,13], [14,15,16]])
print(myArray.reshape(3,2),'\n')

#MATH
#Use this array for the following practice:
#myArray = np.arange(10)
#1. Find the square of every number in array
#2. Find the square root of every number in array
#3. Multiply the square of each number in array with its respective square root
print('Math')
print('1: ')
myArray=np.arange(10)
print(np.square(myArray),'\n')
print('2: ')
print(np.sqrt(myArray),'\n')
print('3: ')
print(np.square(myArray)*np.sqrt(myArray),'\n')

#ADDING ELEMENTS
#Use this array for the following practice:
#myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
#1. Add a new row of elements containing 20, 21 and 22
#2. Add a new column of elements containing 30, 40 and 50
print('Adding elements')
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print('1: ')
first_adding=np.array([20,21,22])
print(np.vstack([myArray,first_adding]),'\n')
print('2: ')
second_adding=np.array([[30],[40],[50]])
print(np.hstack([myArray,second_adding]),'\n')

#INSERTING ELEMENTS
#1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
#2. Add 2 rows of 2 to the answer from part 1
#3. Remove the last column
#4. Remove the last row
print('Inserting elements')
print('1: ')
myArray = np.zeros((2,2))
array_with_ones=np.array([[1],[1]])
newarray=(np.hstack([myArray,array_with_ones]))
print(newarray,'\n')
print('2: ')
array_with_twos=np.array([[2,2,2],[2,2,2]])
stacked_array=np.vstack([newarray,array_with_twos])
print(stacked_array,'\n')
print('3: ')
removed_column_array=stacked_array[:,:-1]
print(removed_column_array,'\n')
print('4: ')
removed_row_array=removed_column_array[:-1,:]
print(removed_row_array,'\n')

#DELETING ELEMENTS
#Remove the elements from the middle column of this array:
#myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
#Your codes should look like this:
#[[1 3]
#[4 6]
#[9 7]]
print('Deleting elements')
myArray=np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print('1: ')
print(np.delete(myArray,1,axis=1),'\n')

#TEST EXERCISE
#Replace all odd numbers in the given array with -1
#Start with:
#exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Desired output:
#[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
print('Test exercise')
print('1: ')
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1%2!=0]=-1
print(exercise_1,'\n')

#Convert a 1-D array into a 2-D array with 3 rows
#Start with:
#exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
#Desired output:
#[[ 0, 1, 2]
#[3, 4, 5]
#[6, 7, 8]]
print('2: ')
exercise_2=np.array([0,1,2,3,4,5,6,7,8])
print(exercise_2.reshape(3,3),'\n')

#Add 202 to all the values in given array
#Start with:
#exercise_3 = np.arange(4).reshape(2,-1)
#Desired output:
#[[202, 203]
#[204, 205]]
print('3: ')
exercise_3 = np.arange(4).reshape(2,-1)
exercise_3 += 202
print(exercise_3,'\n')

#Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
#Sample of desired output:
#[36, 30, 36, 38, 31, 35, 36, 30, 32, 34]
random_array=np.random.randint(30,41,size=(1,10))
print('4: ')
print(random_array,'\n')

#Find the positions of:
#elements in x where its value is more than its corresponding element in y, and
#elements in x where its value is equals to its corresponding element in y.
#Start with these:
#x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
#y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
#Desired output:
#(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),)
print('5: ')
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
bigger_position=np.where(x>y)
equal_position=np.where(x==y)
print(bigger_position,'and',equal_position,'\n')

#Extract the first four columns of this 2-D array
#Start with this:
#exercise_6 = np.arange(100).reshape(5,-1)
#Desired output:
#[[ 0 1 2 3]
#[20 21 22 23]
#[40 41 42 43]
#[60 61 62 63]
#[80 81 82 83]]
exercise_6 = np.arange(100).reshape(5,-1)
extracted_array=exercise_6[:,:4]
print('6: ')
print(extracted_array)


Creating arrays
1:
[[11 12 13 14]
 [15 16 17 18]] 

Use the appropriate functions to solve the following questions
1: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

3:
[[ 4  5  6  7  8  9 10 11 12 13]] 

4:
[0.  1.5 3.  4.5] 

5: 
[[4 4]
 [4 4]] 

6i: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

6ii: 
[[10  0]
 [ 0 12]] 

7: 
[[2.47771948 9.99449097 7.41993241]
 [9.78296091 0.2912015  7.52367464]
 [0.82651134 8.63019331 8.82388763]] 

8: 
[[14 13 14]
 [11 15 14]
 [16 15 19]] 

Slicing arrays
1a: 
[[11 12]] 

1b: 
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]] 

2: 
[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0] 

Reshaping
1: 
[[11 12]
 [13 14]
 [15 16]] 

Math
1: 
[ 0  1  4  9 16 25 36 49 64 81] 

2: 
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

3: 
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.1