In [30]:
import numpy as np
#creating arrays
#1.Create a rank 2 (2D) array that resembles the matrix below.
#[[11 12 13 14]
#[15 16 17 18]]
the_2d_array=np.array([[11,12,13,14],[15,16,17,18]])
print('1:')
print(the_2d_array,'\n')
#use the appropriate functions to solve the following questions
#1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
#[[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]
#[0. 0. 0.]]
first_array=np.zeros((4,3))
print('2:')
print(first_array,'\n')
#2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
#[[1. 1. 1. 1.]
#[1. 1. 1. 1.]
#[1. 1. 1. 1.]]
second_array=np.ones((3,4))
print('3:')
print(second_array,'\n')
#3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
#[4 5 6 7 8 9 10 11 12 13]
third_array=np.array([[4,5,6,7,8,9,10,11,12,13]])
print('4:')
print(third_array,'\n')
#4. Create an array containing
#[0., 1.5, 3., 4.5]
fourth_array=np.array([0,1.5,3,4.5],dtype=np.double)
print('5:')
print(fourth_array)

1:
[[11 12 13 14]
 [15 16 17 18]] 

2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

3:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

4:
[[ 4  5  6  7  8  9 10 11 12 13]] 

5:
[0.  1.5 3.  4.5]
